-- DDL for Tambalin Application

-- This script has been modified to account for a pre-existing 'profiles' table.
-- It alters the table and adjusts security policies accordingly.

-- ---------------------------------------------------------------------
-- Table: profiles
-- Description: The 'profiles' table already existed. We are altering it
-- to add the missing 'phone_number' column.
-- ---------------------------------------------------------------------

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS phone_number text;

-- The original 'CREATE TABLE public.profiles' command was removed to prevent errors.

-- ---------------------------------------------------------------------
-- Table: shops
-- Description: Contains all data related to vehicle repair shops (bengkel).
-- ---------------------------------------------------------------------
create table public.shops (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  latitude double precision not null,
  longitude double precision not null,
  photo_urls text[],
  whatsapp_number text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

comment on table public.shops is 'Information about repair shops (bengkel).';
comment on column public.shops.latitude is 'GPS latitude for location.';
comment on column public.shops.longitude is 'GPS longitude for location.';
comment on column public.shops.photo_urls is 'Array of URLs for shop photos stored in Supabase Storage.';

-- ---------------------------------------------------------------------
-- Table: mechanics
-- Description: Lists mechanics and links them to their respective shops.
-- ---------------------------------------------------------------------
create table public.mechanics (
  id bigint generated by default as identity primary key,
  name text not null,
  shop_id bigint not null references public.shops on delete cascade,
  specialty text,
  created_at timestamp with time zone not null default now()
);

comment on table public.mechanics is 'Mechanics associated with a specific repair shop.';
comment on column public.mechanics.shop_id is 'Foreign key linking to the shops table.';

-- ---------------------------------------------------------------------
-- Table: reviews
-- Description: Stores user-submitted reviews and ratings for shops.
-- ---------------------------------------------------------------------
create table public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles on delete cascade,
  shop_id bigint not null references public.shops on delete cascade,
  rating smallint not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone not null default now()
);

comment on table public.reviews is 'User reviews and ratings for repair shops.';
comment on column public.reviews.user_id is 'Foreign key linking to the user who wrote the review.';
comment on column public.reviews.rating is 'Star rating from 1 to 5.';


-- ---------------------------------------------------------------------
-- Row Level Security (RLS) Setup
-- Note: It's safe to run these commands even if RLS or policies already exist.
-- Supabase handles 'CREATE POLICY' gracefully, and 'ENABLE RLS' will just be a no-op if already enabled.
-- ---------------------------------------------------------------------

-- Enable RLS for all tables
alter table public.profiles enable row level security;
alter table public.shops enable row level security;
alter table public.mechanics enable row level security;
alter table public.reviews enable row level security;

-- ---- POLICIES: profiles ----
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- ---- POLICIES: shops ----
create policy "Shops are viewable by everyone." on public.shops
  for select using (true);

-- Using `role::text` to cast the custom 'user_role' enum type for comparison.
create policy "Admins can manage shops." on public.shops
  for all using (exists (select 1 from public.profiles where id = auth.uid() and role::text = 'admin'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role::text = 'admin'));

-- ---- POLICIES: mechanics ----
create policy "Mechanics are viewable by everyone." on public.mechanics
  for select using (true);

-- Using `role::text` to cast the custom 'user_role' enum type for comparison.
create policy "Admins can manage mechanics." on public.mechanics
  for all using (exists (select 1 from public.profiles where id = auth.uid() and role::text = 'admin'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role::text = 'admin'));

-- ---- POLICIES: reviews ----
create policy "Reviews are viewable by everyone." on public.reviews
  for select using (true);

create policy "Authenticated users can create reviews." on public.reviews
  for insert with check (auth.role() = 'authenticated');

create policy "Users can update their own reviews." on public.reviews
  for update using (auth.uid() = user_id);

create policy "Users can delete their own reviews." on public.reviews
  for delete using (auth.uid() = user_id);
